name: Main Workflow
on: [push]
jobs:
  build:
    name: Run Local k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6-script.js
          flags: --vus 50 --duration 10s
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
